// commitlint config for imboy-admin-frontend (React / TypeScript / Vite)
// .cjs 扩展名是必须的：本仓 package.json 设了 "type": "module"
// Generated by quality-loop T1.2 on 2026-05-08
// See ../.claude/plans/quality-loop.md

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-case': [0],
    'header-max-length': [2, 'always', 100],
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'refactor', 'docs', 'test', 'chore', 'perf', 'ci', 'style', 'build', 'revert'],
    ],
  },
};
